/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QuestionDB.java
 *
 * Created on Nov 16, 2010, 1:29:00 AM
 */

/**
 *
 * @author Tytanium
 */
public class QuestionDB extends javax.swing.JFrame {

    /** Creates new form QuestionDB */
    public QuestionDB() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jFrame1.setName("jFrame1"); // NOI18N

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame2.setName("jFrame2"); // NOI18N

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "CPE102", "1", "5", "Never", "Check Boxes", "", null, "None"},
                {"2", "CPE102", "3", "15", "Never", "Drawn Answer", null, null, "None"},
                {"3", "CPE102", "4", "15", "Never", "Essay", null, null, "None"},
                {"4", "CPE102", "2", "5", "Never", "Fill in the Blank", null, null, "None"},
                {"5", "CPE102", "4", "6", "Never", "Matching", null, null, "None"},
                {"6", "CPE102", "5", "5", "Never", "Multiple Choice", null, null, "None"},
                {"7", "CPE102", "2", "4", "Never", "Point and Click", null, null, "None"},
                {"8", "CPE102", "5", "20", "Never", "Programming", null, null, "None"},
                {"9", "CPE102", "3", "5", "Never", "Short Answer", null, null, "None"},
                {"10", "CPE102", "1", "2", "Never", "True/False", null, null, null},
                {"11", "", null, null, null, null, null, null, null},
                {"12", "", null, null, null, null, null, null, null},
                {"13", "", null, null, null, null, null, null, null},
                {"14", "", null, null, null, null, null, null, null},
                {"15", "", null, null, null, null, null, null, null},
                {"16", "", null, null, null, null, null, null, null},
                {"17", "", null, null, null, null, null, null, null},
                {"18", "", null, null, null, null, null, null, null},
                {"19", "", null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Class", "Difficulty", "Time Allowed", "Last Used", "Type of Question", "Question", "Answer", "HTML File"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setName("jTable1"); // NOI18N
        jTable1.setPreferredSize(new java.awt.Dimension(600, 300));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jTable1.columnModel.title6")); // NOI18N
        jTable1.getColumnModel().getColumn(2).setHeaderValue(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jTable1.columnModel.title1")); // NOI18N
        jTable1.getColumnModel().getColumn(3).setHeaderValue(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jTable1.columnModel.title2")); // NOI18N
        jTable1.getColumnModel().getColumn(4).setHeaderValue(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jTable1.columnModel.title3")); // NOI18N
        jTable1.getColumnModel().getColumn(5).setHeaderValue(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jTable1.columnModel.title4")); // NOI18N
        jTable1.getColumnModel().getColumn(6).setHeaderValue(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jTable1.columnModel.title8")); // NOI18N
        jTable1.getColumnModel().getColumn(7).setHeaderValue(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jTable1.columnModel.title5")); // NOI18N
        jTable1.getColumnModel().getColumn(8).setHeaderValue(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jTable1.columnModel.title7")); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1223;
        gridBagConstraints.ipady = 661;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 11, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jScrollBar1.setName("jScrollBar1"); // NOI18N
        jScrollBar1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBar1AdjustmentValueChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 683;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 11, 10);
        getContentPane().add(jScrollBar1, gridBagConstraints);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jMenu2.text")); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jMenu3.text")); // NOI18N
        jMenu3.setName("jMenu3"); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setName("jMenu4"); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu5.setText(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jMenu5.text")); // NOI18N
        jMenu5.setName("jMenu5"); // NOI18N
        jMenuBar1.add(jMenu5);

        jMenu6.setText(org.jdesktop.application.Application.getInstance(questiondb.QuestionDBApp.class).getContext().getResourceMap(QuestionDB.class).getString("jMenu6.text")); // NOI18N
        jMenu6.setName("jMenu6"); // NOI18N
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollBar1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBar1AdjustmentValueChanged
        // TODO add your handling code here:
}//GEN-LAST:event_jScrollBar1AdjustmentValueChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
