proj3: freq.h File Reference
freq.h File Reference
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <dirent.h>
#include <strings.h>
#include <libgen.h>
Data Structures
struct word
Defines
#define BUFL 1024
#define CHARV 48
#define LONGWORD 20
#define MAXENTRY 1000002
#define STOPIT 999423
#define FATALCALL(cond, complaint)
#define FATALTEST(cond, complaint)
#define FATALTEST2(cond, complaint, p1)
#define FATALTEST3(cond, complaint, p1, p2)
Typedefs
typedef struct word word_t
Functions
unsigned long hash (unsigned char *str)
Create a hash value for the string, used for storage.
void newfile (char *pathname, word_t **array)
int newword (int fd, char *pathname, char theword[], char *buffer, int *location, int *buflength)
int newchar (char *letter, char *buffer, int location)
int newblock (int fd, char *buffer)
word_t * makeword ()
int compareword (const void *first, const void *second)
Detailed Description
 CPE 357 Winter 2010
 -------------------
 Header for project 3
 Last Modified: Wed Feb  3 09:34:33 PST 2010
Author:
Tyler Holland
Define Documentation
#define FATALCALL (cond, complaint)
Value:
if (cond) {           \
        perror(complaint);  \
        exit(EXIT_FAILURE); \
      }
#define FATALTEST (cond, complaint)
Value:
if (cond) {           \
        fputs(complaint, stderr);  \
        exit(EXIT_FAILURE); \
      }
#define FATALTEST2 (cond, complaint, p1)
Value:
if (cond) {           \
        fprintf(stderr, complaint, p1);  \
        exit(EXIT_FAILURE); \
      }
#define FATALTEST3 (cond, complaint, p1, p2)
Value:
if (cond) {           \
        fprintf(stderr, complaint, p1, p2);  \
        exit(EXIT_FAILURE); \
      }
Function Documentation
int compareword (const void * first, const void * second)
Parameters:
first first word_t pointer
second second word_t pointer
Returns:
1 on first > second, 0 on first = second, -1 on first < second
unsigned long hash (unsigned char * str)
Create a hash value for the string, used for storage.
Parameters:
*str The string to get the hash value of
Returns:
hash value of the string
References hash().
Referenced by hash(), and newfile().
int newblock (int fd, char * buffer)
Parameters:
fd the file descriptor
buffer the latest block of bytes
Returns:
number of bytes read in to buffer, or the return value of read
Referenced by newword().
int newchar (char * letter, char * buffer, int location)
Parameters:
letter the new character
buffer the latest block of bytes
location the current location in the buffer
Returns:
1 on successful character got, 0 if it was not an alphabetic character
Referenced by newword().
void newfile (char * pathname, word_t ** array)
Parameters:
pathname The file or directory path name
array The array of word_t pointers
References hash(), and newword().
Referenced by main().
int newword (int fd, char * pathname, char theword[], char * buffer, int * location, int * buflength)
Parameters:
fd the file descriptor
theword a pointer to the word to pass back.
location the current location in the buffer block
buflength total length of the buffer
Returns:
-2 on failure, -1 on no word, 0-999999 on success, based on # of letters beyond the 20 char max.
References newblock(), and newchar().
Referenced by newfile().