proj3: hash.c File Reference
hash.c File Reference
Functions
unsigned long hash (unsigned char *str)
Create a hash value for the string, used for storage.
Detailed Description
CPE 357 Winter 2010
  -------------------
  hash: Uses Dan Bernstein's string hash algorithm shown at http://www.cse.yorku.ca/~oz/hash.html
    Algorithm also availiable at http://fr.wikipedia.org/wiki/Table_de_hachage#Fonction_de_Hachage
Author:
 Tyler Holland
  Last Modified: Wed Feb  3 09:34:33 PST 2010
Function Documentation
unsigned long hash (unsigned char * str)
Create a hash value for the string, used for storage.
Parameters:
*str The string to get the hash value of
Returns:
hash value of the string
References hash().
Referenced by hash(), and newfile().