mypgm: mypgm.h File Reference
mypgm.h File Reference
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <math.h>
Defines
#define MAXVALUE 65535
#define BUFL 1024
#define LONGHOLD 10
#define SMALLBYTE 256
#define PRINTWIDTH 10
#define STORAGE 300
#define OTHERERR 1
#define CMDLINEERR 2
#define MAXVALOUTERR 4
#define MAXVALOVERERR 8
#define MULTINFILEERR 16
#define INCFILEERR 32
#define OUTPUTFORMERR 64
#define FATALCALL(cond, complaint)
#define FATALTEST(cond, complaint)
#define FATALTEST2(cond, complaint, p1)
#define FATALTEST3(cond, complaint, p1, p2)
Functions
void usage (char *cmd)
Print the usage message for this program.
int getval (char *p)
Convert the val size.
void freeall (int width, int **array)
FREE ABSOLUTELY EVERYTHING.
int brightenfunc (int maxval, int **array, int value, int height, int width)
A function to do all work for brighten.
int darkenfunc (int maxval, int **array, int value, int height, int width)
A function to do all work for darken.
void smoothfunc (int **array, int height, int width)
A function to do all work for smooth.
int maxvaledit (int maxval, int readmaxval, int **array, int height, int width)
A function to do all work for calculating max values.
int divandround (int value1, int value2)
int round (double number)
Detailed Description
 CPE 357 Winter 2010
 -------------------
 Header for Project 4, mypgm
 Last Modified: Sat Feb 13 10:19:46 PST 2010
Author:
Tyler Holland
Define Documentation
#define FATALCALL (cond, complaint)
Value:
if (cond) {           \
        perror(complaint);  \
        exit(EXIT_FAILURE); \
      }
#define FATALTEST (cond, complaint)
Value:
if (cond) {           \
        fprintf(stderr, complaint);  \
        exit(EXIT_FAILURE); \
      }
#define FATALTEST2 (cond, complaint, p1)
Value:
if (cond) {           \
        fprintf(stderr, complaint, p1);  \
        exit(EXIT_FAILURE); \
      }
#define FATALTEST3 (cond, complaint, p1, p2)
Value:
if (cond) {           \
        fprintf(stderr, complaint, p1, p2);  \
        exit(EXIT_FAILURE); \
      }
Function Documentation
int brightenfunc (int maxval, int ** array, int value, int height, int width)
A function to do all work for brighten.
Parameters:
maxval The current max value
array The array that stores the image
value The amount to brighten
height The height of the image
width The width of the image
Returns:
The new max value
References freeall().
int darkenfunc (int maxval, int ** array, int value, int height, int width)
A function to do all work for darken.
Parameters:
maxval The current max value
array The array that stores the image
value The amount to darken
height The height of the image
width The width of the image
Returns:
The new max value
References freeall().
int divandround (int value1, int value2)
Parameters:
value1 The value to be devided by
value2 The value to divide by
Returns:
The rounded answer
Referenced by smoothfunc().
void freeall (int width, int ** array)
FREE ABSOLUTELY EVERYTHING.
Parameters:
width For freeing the array
array The array that holds the image
Referenced by brightenfunc(), darkenfunc(), and smoothfunc().
int getval (char * p)
Convert the val size.
This does not check for overflow. Aborts on non-digit characters.
Parameters:
p a pointer to a decimal-only string.
Returns:
the numeric value of the string.
int maxvaledit (int maxval, int readmaxval, int ** array, int height, int width)
A function to do all work for calculating max values.
Parameters:
maxval The current max value
readmaxval The max value from the file itself
array The array that holds the image
height The height of the image
width The width of the image
Returns:
The new max value
References round().
int round (double number)
Parameters:
number A double to round, following project 4 rules
Returns:
The rounded number, as an int
Referenced by maxvaledit().
void smoothfunc (int ** array, int height, int width)
A function to do all work for smooth.
Parameters:
array The array that stores the image
height The height of the image
width The width of the image
References divandround(), and freeall().
void usage (char * cmd)
Print the usage message for this program.
Parameters:
cmd the command name.