proj4: mypgm.c File Reference
mypgm.c File Reference
#include "mypgm.h"
Functions
int main (int argc, char *argv[])
void usage (char *cmd)
Print the usage message for this program.
int getval (char *p)
Convert the val size.
void freeall (int width, int **array)
FREE ABSOLUTELY EVERYTHING.
Detailed Description
CPE 357 Winter 2010
  -------------------
  mypgm: a program that reads and writes PGM (Portable GrayMap) files,
  and performs simple operations on them.
Author:
Tyler Holland
  Last Modified: Sat Feb 13 09:34:33 PST 2010
Function Documentation
void freeall (int width, int ** array)
FREE ABSOLUTELY EVERYTHING.
Parameters:
width For freeing the array
array The array that holds the image
Referenced by brightenfunc(), darkenfunc(), and smoothfunc().
int getval (char * p)
Convert the val size.
This does not check for overflow. Aborts on non-digit characters.
Parameters:
p a pointer to a decimal-only string.
Returns:
the numeric value of the string.
void usage (char * cmd)
Print the usage message for this program.
Parameters:
cmd the command name.