proj4: ops.c File Reference
ops.c File Reference
#include "mypgm.h"
Functions
int brightenfunc (int maxval, int **array, int value, int height, int width)
A function to do all work for brighten.
int darkenfunc (int maxval, int **array, int value, int height, int width)
A function to do all work for darken.
void smoothfunc (int **array, int height, int width)
A function to do all work for smooth.
int maxvaledit (int maxval, int readmaxval, int **array, int height, int width)
A function to do all work for calculating max values.
int divandround (int value1, int value2)
int round (double number)
Detailed Description
CPE 357 Winter 2010
  -------------------
  ops: has all of the operations for mypgm
Author:
Tyler Holland
  Last Modified: Sat Feb 13 09:34:33 PST 2010
Function Documentation
int brightenfunc (int maxval, int ** array, int value, int height, int width)
A function to do all work for brighten.
Parameters:
maxval The current max value
array The array that stores the image
value The amount to brighten
height The height of the image
width The width of the image
Returns:
The new max value
References freeall().
int darkenfunc (int maxval, int ** array, int value, int height, int width)
A function to do all work for darken.
Parameters:
maxval The current max value
array The array that stores the image
value The amount to darken
height The height of the image
width The width of the image
Returns:
The new max value
References freeall().
int divandround (int value1, int value2)
Parameters:
value1 The value to be devided by
value2 The value to divide by
Returns:
The rounded answer
Referenced by smoothfunc().
int maxvaledit (int maxval, int readmaxval, int ** array, int height, int width)
A function to do all work for calculating max values.
Parameters:
maxval The current max value
readmaxval The max value from the file itself
array The array that holds the image
height The height of the image
width The width of the image
Returns:
The new max value
References round().
int round (double number)
Parameters:
number A double to round, following project 4 rules
Returns:
The rounded number, as an int
Referenced by maxvaledit().
void smoothfunc (int ** array, int height, int width)
A function to do all work for smooth.
Parameters:
array The array that stores the image
height The height of the image
width The width of the image
References divandround(), and freeall().