proj3: readwords.c File Reference
readwords.c File Reference
#include "freq.h"
Functions
void newfile (char *pathname, word_t **array)
int newword (int fd, char *pathname, char theword[], char *buffer, int *location, int *buflength)
int newchar (char *letter, char *buffer, int location)
int newblock (int fd, char *buffer)
Detailed Description
 CPE 357 Winter 2010
 -------------------
 Reads in words for use in freq.c
 Last Modified: Wed Feb  3 09:34:33 PST 2010
Author:
Tyler Holland
Function Documentation
int newblock (int fd, char * buffer)
Parameters:
fd the file descriptor
buffer the latest block of bytes
Returns:
number of bytes read in to buffer, or the return value of read
Referenced by newword().
int newchar (char * letter, char * buffer, int location)
Parameters:
letter the new character
buffer the latest block of bytes
location the current location in the buffer
Returns:
1 on successful character got, 0 if it was not an alphabetic character
Referenced by newword().
void newfile (char * pathname, word_t ** array)
Parameters:
pathname The file or directory path name
array The array of word_t pointers
References hash(), and newword().
Referenced by main().
int newword (int fd, char * pathname, char theword[], char * buffer, int * location, int * buflength)
Parameters:
fd the file descriptor
theword a pointer to the word to pass back.
location the current location in the buffer block
buflength total length of the buffer
Returns:
-2 on failure, -1 on no word, 0-999999 on success, based on # of letters beyond the 20 char max.
References newblock(), and newchar().
Referenced by newfile().