-- ProjNav VHDL simulation template: procedure2test_tb_0.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
